# This file is part of the CARTA Image Viewer: https://github.com/CARTAvis/carta-zarr
# Copyright 2026- Academia Sinica Institute of Astronomy and Astrophysics (ASIAA),
# Associated Universities, Inc. (AUI) and the Inter-University Institute for Data Intensive Astronomy (IDIA)
# SPDX-License-Identifier: GPL-3.0-or-later

__ZN5carta4zarr*
__ZNK5carta4zarr*
__ZTIN5carta4zarr*
__ZTSN5carta4zarr*
__ZTVN5carta4zarr*
